name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> $GITHUB_ENV
          echo "MICRO=${{ secrets.MICRO }}" >> $GITHUB_ENV
          echo "ENV=${{ secrets.ENV }}" >> $GITHUB_ENV
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
